@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center py-3 mb-4"><div><h4 class="fw-bold mb-1">Dashboard Anggota GKM</h4><p class="text-muted mb-0">Ringkasan pekerjaan input Monev dan RTM Anda.</p></div><div><a href="{{ route('ringkasan-perkuliahan.create') }}" class="btn btn-primary">Input Ringkasan</a> <a href="{{ route('notulen-rtm.create') }}" class="btn btn-outline-primary">Buat Notulen</a></div></div>
<div class="row">@foreach($stats as $item)<x-dashboard-stat :item="$item" />@endforeach</div>
<div class="row mb-4"><div class="col-lg-5 mb-4"><div class="card h-100"><h5 class="card-header">Perlu Diselesaikan</h5><div class="card-body">
@foreach(['ringkasan_draft'=>'Ringkasan Draft','ringkasan_ditolak'=>'Ringkasan Ditolak','temuan_draft'=>'Temuan Draft','notulen_draft'=>'Notulen Draft','notulen_ditolak'=>'Notulen Ditolak'] as $key=>$label)<div class="d-flex justify-content-between mb-2"><span>{{ $label }}</span><span class="badge bg-label-{{ str_contains($key,'ditolak') ? 'danger' : 'secondary' }}">{{ $statusPekerjaan[$key] }}</span></div>@endforeach
</div></div></div><div class="col-lg-7 mb-4"><div class="card h-100"><h5 class="card-header">Jadwal Monev Aktif</h5><div class="list-group list-group-flush">@forelse($jadwalMonevAktif as $item)<a href="{{ route('jadwal-monev.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->semester?->label }}</strong> — {{ $item->termin?->nama_termin }}<br><small>{{ $item->tanggal_mulai?->format('d-m-Y') }} s.d. {{ $item->tanggal_selesai?->format('d-m-Y') }}</small></a>@empty<div class="p-3 text-muted">Tidak ada jadwal aktif.</div>@endforelse</div></div></div></div>
<div class="row"><div class="col-lg-4 mb-4"><div class="card h-100"><h5 class="card-header">Ringkasan Terbaru</h5><div class="list-group list-group-flush">@forelse($ringkasanTerbaru as $item)<a href="{{ route('ringkasan-perkuliahan.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->perkuliahan?->mataKuliah?->nama_mk }}</strong><br><small>{{ $item->perkuliahan?->kelas?->nama_kelas }} · {{ ucfirst($item->status) }}</small></a>@empty<div class="p-3 text-muted">Belum ada data.</div>@endforelse</div></div></div>
<div class="col-lg-4 mb-4"><div class="card h-100"><h5 class="card-header">Temuan Terbaru</h5><div class="list-group list-group-flush">@forelse($temuanTerbaru as $item)<a href="{{ route('temuan-evaluasi.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->kode_temuan }}</strong><br>{{ Str::limit($item->pernyataan,70) }}<br><small>{{ ucfirst($item->status) }}</small></a>@empty<div class="p-3 text-muted">Belum ada data.</div>@endforelse</div></div></div>
<div class="col-lg-4 mb-4"><div class="card h-100"><h5 class="card-header">Notulen Terbaru</h5><div class="list-group list-group-flush">@forelse($notulenTerbaru as $item)<a href="{{ route('notulen-rtm.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->jadwalRtm?->judul }}</strong><br><small>{{ $item->jadwalRtm?->semester?->label }} · {{ ucfirst($item->status) }}</small></a>@empty<div class="p-3 text-muted">Belum ada data.</div>@endforelse</div></div></div></div>
@endsection
