@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center py-3 mb-4"><div><h4 class="fw-bold mb-1">Dashboard Koordinator Prodi</h4><p class="text-muted mb-0">Gambaran menyeluruh pelaksanaan mutu program studi.</p></div><a href="{{ route('ami.index') }}" class="btn btn-primary">Lihat Rekapan AMI</a></div>
<div class="row">@foreach($stats as $item)<x-dashboard-stat :item="$item" />@endforeach</div>
<div class="row mb-4"><div class="col-lg-7 mb-4">@include('dashboard.partials.capaian')</div><div class="col-lg-5 mb-4"><div class="card h-100"><h5 class="card-header">AMI Terbaru</h5><div class="list-group list-group-flush">@forelse($amiTerbaru as $item)<a href="{{ route('ami.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->tahunAkademik?->nama }}</strong> — {{ Str::limit($item->temuan,80) }}<br><small>{{ $item->dokumenAmis->count() }} bukti · {{ ucfirst($item->status) }}</small></a>@empty<div class="p-3 text-muted">Belum ada AMI.</div>@endforelse</div></div></div></div>
<div class="row"><div class="col-lg-6 mb-4"><div class="card h-100"><h5 class="card-header">Ringkasan Monev Terverifikasi</h5><div class="list-group list-group-flush">@forelse($ringkasanTerbaru as $item)<a href="{{ route('ringkasan-perkuliahan.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->perkuliahan?->mataKuliah?->nama_mk }}</strong> — {{ $item->perkuliahan?->kelas?->nama_kelas }}<br><small>{{ $item->jadwalMonev?->semester?->label }}</small></a>@empty<div class="p-3 text-muted">Belum ada ringkasan terverifikasi.</div>@endforelse</div></div></div>
<div class="col-lg-6 mb-4"><div class="card h-100"><h5 class="card-header">Temuan Terbuka</h5><div class="list-group list-group-flush">@forelse($temuanTerbuka as $item)<a href="{{ route('temuan-evaluasi.show',$item) }}" class="list-group-item list-group-item-action"><strong>{{ $item->kode_temuan }}</strong> — {{ Str::limit($item->pernyataan,90) }}<br><small>{{ $item->dosen?->nama_dosen }} · {{ $item->evaluasiIndikator?->semester?->label }}</small></a>@empty<div class="p-3 text-muted">Tidak ada temuan terbuka.</div>@endforelse</div></div></div></div>
<div class="card"><h5 class="card-header">RTM Terbaru</h5><div class="table-responsive"><table class="table"><thead><tr><th>RTM</th><th>Semester</th><th>Tanggal</th><th>Keputusan</th><th>Status</th></tr></thead><tbody>@forelse($rtmTerbaru as $item)<tr><td>{{ $item->judul }}</td><td>{{ $item->semester?->label }}</td><td>{{ $item->tanggal?->format('d-m-Y') }}</td><td>{{ $item->notulenRtm?->keputusanRtms?->count() ?? 0 }}</td><td><span class="badge bg-label-primary">{{ ucfirst($item->status) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center">Belum ada RTM.</td></tr>@endforelse</tbody></table></div></div>
@endsection
